/**
 * AxUX React UI Framework with Tailwind CSS
 * @author    : Adarsh Pastakia
 * @version   : 4.0.0
 * @copyright : 2024
 * @license   : MIT
 */

const plugin = require("tailwindcss/plugin");
const colors = require("tailwindcss/colors");
const theme = require("tailwindcss/defaultTheme");

module.exports = plugin(
  ({ addUtilities, matchUtilities, addBase, theme }) => {
    matchUtilities({
      "grid-area": (value) => ({
        gridArea: value,
      }),
    });
    addUtilities({
      ".bg-alternate": {},
      ".paper": {},
      ".centered": {},
      ".show-xl-only": {},
      ".show-lg-only": {},
      ".show-md-only": {},
      ".show-sm-only": {},
      ".show-xs-only": {},
      ".show-xl": {},
      ".show-lg": {},
      ".show-md": {},
      ".show-sm": {},
      ".show-xs": {},
      ".hide-scroll": {},
      ".hide-xl-only": {},
      ".hide-lg-only": {},
      ".hide-md-only": {},
      ".hide-sm-only": {},
      ".hide-xs-only": {},
      ".hide-xl": {},
      ".hide-lg": {},
      ".hide-md": {},
      ".hide-sm": {},
      ".hide-xs": {},
      ".grid-layout": {
        display: "grid",
        "grid-area": "content",
        "grid-template-areas":
          '"loader loader loader" "head head head" "side-s content side-e" "foot foot foot"',
        "grid-template-columns": "auto 1fr auto",
        "grid-template-rows": "auto auto 1fr auto",
        overflow: "hidden",
      },
      ".z-1": { "z-index": 1 },
      ".z-2": { "z-index": 2 },
      ".grid-area-content": { "grid-area": "content" },
      ".grid-area-head": { "grid-area": "head" },
      ".grid-area-foot": { "grid-area": "foot" },
      ".grid-area-side-s": { "grid-area": "side-s" },
      ".grid-area-side-e": { "grid-area": "side-e" },
      ".grid-area-body": { "grid-area": "body" },
      ".overflow-wrap": {
        "overflow-wrap": "anywhere",
        "word-break": "normal",
        "text-wrap": "wrap",
      },
      ".align-start": {
        "text-align": "start",
      },
      ".align-end": {
        "text-align": "end",
      },
      ".fixed-numbers": {
        "font-variant-numeric": "tabular-nums",
      },
      ".btn-gradient": {
        "background-image":
          "linear-gradient(180deg,rgb(255 255 255 / 5%) 0%,transparent 35%,transparent 63%,rgb(0 0 0 / 5%) 100%)",
      },
    });
  },
  {
    darkMode: ["class", '[data-color-scheme="dark"]'],
    theme: {
      fontFamily: {
        sans: [
          "Avenir Next",
          "Avenir",
          "Noto Sans",
          "Roboto",
          "Helvetica Neue",
          "Segoe UI",
          "Arial",
          "sans-serif",
          "BlinkMacSystemFont",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        serif: [
          "Noto Serif",
          "Georgia",
          "Cambria",
          "Times New Roman",
          "Times",
          "serif",
        ],
        mono: [
          "Noto Sans Mono",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        reset: ["1rem", { lineHeight: "1.5rem" }],
        md: ["1.125rem", { lineHeight: "1.5rem" }],
        lg: ["1.25rem", { lineHeight: "1.75rem" }],
        xl: ["1.5rem", { lineHeight: "2rem" }],
        "2xl": ["1.75rem", { lineHeight: "2.25rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["3rem", { lineHeight: "1" }],
        "6xl": ["3.75rem", { lineHeight: "1" }],
        "7xl": ["4.5rem", { lineHeight: "1" }],
        "8xl": ["6rem", { lineHeight: "1" }],
        "9xl": ["8rem", { lineHeight: "1" }],
      },
      extend: {
        colors: {
          black: "#091414",
          white: "#fcfcfd",
          silver: "#8D90A1",
          steel: "#5d8aa8",
          olive: "#54908e",
          sand: "#948481",
          info: "#00bfff",
          danger: "#f24c3d",
          success: "#44bc69",
          warning: "#edaa00",
          scarlet: "#d7323a",
          pumpkin: "#ff781c",
          jade: "#22aa85",
          denim: "#399bec",
          iris: "#4862c8",
          lilac: "#aa66cf",
          coral: "#f43f7b",
          wood: "#a37f4f",
        },
        screens: {
          xs: "320px",
        },
        keyframes: {
          cardpulse: {
            "50%": { opacity: 0.5 },
          },
        },
        animation: {
          pulse: "cardpulse 2s cubic-bezier(.4,0,.6,1) infinite",
        },
        aspectRatio: {
          screen: "4 / 3",
        },
        maxWidth: {
          screen: "100vw",
        },
        minWidth: {
          screen: "100vw",
        },
        borderRadius: {
          base: theme.borderRadius.DEFAULT,
          DEFAULT: "var(--ax-rounded)",
        },
        backgroundColor: {
          DEFAULT: "var(--ax-bg)",
          base: "var(--ax-bg-base)",
          dimmed: "var(--ax-bg-dimmed)",
          odd: "var(--ax-bg-base)",
          even: "var(--ax-bg-dimmed)",
          muted: "var(--ax-bg-muted)",
          invert: "var(--ax-bg-invert)",
          input: "var(--ax-input)",
          "input-focus": "var(--ax-input-focus)",
          primary: "var(--ax-bg-primary)",
          accent: "var(--ax-bg-accent)",
          info: "var(--ax-bg-info)",
          danger: "var(--ax-bg-danger)",
          success: "var(--ax-bg-success)",
          warning: "var(--ax-bg-warning)",
          "primary-base": "var(--ax-primary)",
          "accent-base": "var(--ax-accent)",
          "info-base": "var(--ax-info)",
          "danger-base": "var(--ax-danger)",
          "success-base": "var(--ax-success)",
          "warning-base": "var(--ax-warning)",
        },
        textColor: {
          DEFAULT: "var(--ax-text-base)",
          base: "var(--ax-text-base)",
          dimmed: "var(--ax-text-dimmed)",
          muted: "var(--ax-text-muted)",
          placeholder: "var(--ax-placeholder)",
          invert: "var(--ax-text-invert)",
          primary: "var(--ax-text-primary)",
          accent: "var(--ax-text-accent)",
          info: "var(--ax-text-info)",
          danger: "var(--ax-text-danger)",
          success: "var(--ax-text-success)",
          warning: "var(--ax-text-warning)",
          "primary-base": "var(--ax-primary)",
          "accent-base": "var(--ax-accent)",
          "info-base": "var(--ax-info)",
          "danger-base": "var(--ax-danger)",
          "success-base": "var(--ax-success)",
          "warning-base": "var(--ax-warning)",
        },
        boxShadow: {
          xs: "0 1px 1px 0 var(--ax-shadow-base)",
          sm: "0 1px 2px 0 var(--ax-shadow-base)",
          DEFAULT:
            "0 1px 3px 0 var(--ax-shadow-base), 0 1px 2px -1px var(--ax-shadow-base)",
          md: "0 4px 6px -1px var(--ax-shadow-base), 0 2px 4px -2px var(--ax-shadow-base)",
          lg: "0 10px 15px -3px var(--ax-shadow-base), 0 4px 6px -4px var(--ax-shadow-base)",
          xl: "0 20px 25px -5px var(--ax-shadow-base), 0 8px 10px -6px var(--ax-shadow-base)",
          "2xl": "0 25px 50px -12px var(--ax-shadow-base)",
          inner: "inset 0 2px 4px 0 var(--ax-shadow-base)",
          none: "none",
        },
        boxShadowColor: {
          base: "var(--ax-shadow-base)",
          dimmed: "var(--ax-shadow-dimmed)",
          muted: "var(--ax-shadow-muted)",
          invert: "var(--ax-shadow-invert)",
          primary: "var(--ax-shadow-primary)",
          accent: "var(--ax-shadow-accent)",
          info: "var(--ax-shadow-info)",
          danger: "var(--ax-shadow-danger)",
          success: "var(--ax-shadow-success)",
          warning: "var(--ax-shadow-warning)",
          "primary-base": "var(--ax-primary)",
          "accent-base": "var(--ax-accent)",
          "info-base": "var(--ax-info)",
          "danger-base": "var(--ax-danger)",
          "success-base": "var(--ax-success)",
          "warning-base": "var(--ax-warning)",
        },
        borderColor: {
          DEFAULT: "var(--ax-border-base)",
          base: "var(--ax-border-base)",
          dimmed: "var(--ax-border-dimmed)",
          muted: "var(--ax-border-muted)",
          invert: "var(--ax-border-invert)",
          primary: "var(--ax-border-primary)",
          accent: "var(--ax-border-accent)",
          info: "var(--ax-border-info)",
          danger: "var(--ax-border-danger)",
          success: "var(--ax-border-success)",
          warning: "var(--ax-border-warning)",
          "primary-base": "var(--ax-primary)",
          "accent-base": "var(--ax-accent)",
          "info-base": "var(--ax-info)",
          "danger-base": "var(--ax-danger)",
          "success-base": "var(--ax-success)",
          "warning-base": "var(--ax-warning)",
        },
        outlineColor: {
          DEFAULT: "var(--ax-gray)",
          dimmed: "var(--ax-border-dimmed)",
          muted: "var(--ax-border-muted)",
          primary: "var(--ax-primary)",
          accent: "var(--ax-accent)",
          info: "var(--ax-info)",
          danger: "var(--ax-danger)",
          success: "var(--ax-success)",
          warning: "var(--ax-warning)",
        },
        ringColor: {
          DEFAULT: "var(--ax-primary)",
          primary: "var(--ax-primary)",
          accent: "var(--ax-accent)",
          info: "var(--ax-info)",
          danger: "var(--ax-danger)",
          success: "var(--ax-success)",
          warning: "var(--ax-warning)",
        },
        ringOffsetColor: {
          base: "var(--ax-bg)",
        },
      },
    },
  },
);
