name: Build and Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"

      # Runs a set of commands using the runners shell
      - name: Install packages
        run: |
          yarn global add lerna
          yarn bootstrap

      # Runs a set of commands using the runners shell
      - name: Build storybook
        run: |
          yarn build

      - name: Run coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE_TOKEN }}
        with:
          coverageCommand: yarn test

      # Push build folder to gh-pages
      - name: Deploy to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
