name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      # Runs a set of commands using the runners shell
      - name: Install packages
        run: |
          yarn global add lerna
          yarn bootstrap

      - name: Authenticate with Registry
        run: |
          echo "@axux:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Build and publish release
        run: |
          yarn dist
